title: Disclose Géorisques Scraper
description: Custom scraper for georisques.gouv.fr
instructions: ''
type: object
properties:
  run_name: 
    title: Run name
    type: string
    description: Name to identify this run among others on DocumentCloud's interface
  project:
    title: Project
    type: string
    description: >-
      The DocumentCloud project title or ID of the project the documents should
      be uploaded to.  If the project title does not exist, it will be created.
  access_level:
    title: Access level (public, private, organization)
    type: string
    default: private
  # from_year:
  #   title: Year to scrape from
  #   description: leave blank for current year
  #   type: integer
  # to_year:
  #   title: Year to scrape to (included)
  #   description: leave blank for current year
  #   type: integer
  upload_limit:
    title: Maximum number of documents to upload (per run)
    description: 0 for not limit
    type: integer
    default: 0
  time_limit:
    title: Maximum number of minutes the scraper should run
    description: 0 for not limit. Default = 5h45 to prevent hitting the GitHub actions 6h limit.
    type: integer
    default: 345
  dry_run:
    title: Dry run
    type: boolean
    description: If true, documents are not uploaded, and event data is not updated.
    default: true
  upload_event_data:
    title: Upload event_data to DocumentCloud's interface
    type: boolean
    default: false
  event_data_file:
    title: JSON file to load event data from
    type: string
    default: event_data.json
  noindex:
    title: Hide the documents from DocumentCloud & search engine results
    type: boolean
    default: false
  email_report:
    title: Send an email report at the end of each run
    type: boolean
    default: false
  selection_only:
    title: Importer uniquement les documents d'installations listées dans selection_installations.json
    type: boolean
    default: false
required: 
  - project
categories: 
  - monitor
eventOptions:
  name: run_name
  events:
    - hourly
    - daily
    - weekly